import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { PropertiesService } from './properties/properties.service';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  const propertiesService = app.get(PropertiesService);

  const properties = [
    {
      reference: 'REF-001',
      title: 'Casa Moderna com Piscina - 4 Quartos',
      description:
        'Linda casa moderna com 4 quartos, piscina aquecida, jardim amplo e área gourmet completa. Localizada em condomínio fechado com segurança 24h.',
      transactionType: 'comprar',
      propertyType: 'Casa',
      isEmpreendimento: false,
      propertyState: 'novo',
      energyClass: 'A+',
      price: 850000,
      totalArea: 280,
      builtArea: 250,
      usefulArea: 230,
      bedrooms: 4,
      bathrooms: 3,
      hasOffice: false,
      hasLaundry: true,
      garageSpaces: 2,
      constructionYear: 2020,
      distrito: 'Porto',
      concelho: 'Vila Nova de Gaia',
      address: 'Rua das Acácias, 123, Condomínio Jardim Primavera',
      images: [
        'https://exemplo.com/casa1-1.jpg',
        'https://exemplo.com/casa1-2.jpg',
      ],
      status: 'active',
    },
    {
      reference: 'REF-002',
      title: 'Apartamento T2 Centro Histórico',
      description:
        'Apartamento charmoso no centro histórico do Porto, totalmente renovado, com vista para o Douro. Próximo a todos os serviços e transportes.',
      transactionType: 'comprar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'renovado',
      energyClass: 'C',
      price: 320000,
      totalArea: 90,
      builtArea: 85,
      usefulArea: 80,
      bedrooms: 2,
      bathrooms: 1,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 0,
      constructionYear: 1900,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua da Alfândega, 45, 3º andar, Ribeira',
      images: [
        'https://exemplo.com/apt1-1.jpg',
        'https://exemplo.com/apt1-2.jpg',
      ],
      status: 'active',
    },
    {
      reference: 'REF-003',
      title: 'Moradia T3 com Jardim',
      description:
        'Moradia espaçosa T3 com jardim, garagem para 1 carro e zona tranquila. Ideal para famílias.',
      transactionType: 'comprar',
      propertyType: 'Moradia',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'B',
      price: 450000,
      totalArea: 200,
      builtArea: 180,
      usefulArea: 165,
      bedrooms: 3,
      bathrooms: 2,
      hasOffice: false,
      hasLaundry: true,
      garageSpaces: 1,
      constructionYear: 2015,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Avenida da Boavista, 567, Boavista',
      images: ['https://exemplo.com/casa2-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-004',
      title: 'Apartamento T1 Luxo com Piscina',
      description:
        'Apartamento T1 de luxo em condomínio com piscina, ginásio e zona verde. Totalmente equipado e mobilado.',
      transactionType: 'comprar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'novo',
      energyClass: 'A',
      price: 280000,
      totalArea: 70,
      builtArea: 65,
      usefulArea: 60,
      bedrooms: 1,
      bathrooms: 1,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 1,
      constructionYear: 2019,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua de Serralves, 890, Bloco A, 5º andar, Lordelo do Ouro',
      images: ['https://exemplo.com/apt2-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-005',
      title: 'Casa de Campo com 5 Quartos',
      description:
        'Magnífica casa de campo com 5 quartos, piscina, jardim enorme e vista panorâmica. Perfeita para quem procura tranquilidade.',
      transactionType: 'comprar',
      propertyType: 'Casa',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'B',
      price: 1200000,
      totalArea: 380,
      builtArea: 350,
      usefulArea: 320,
      bedrooms: 5,
      bathrooms: 4,
      hasOffice: true,
      hasLaundry: true,
      garageSpaces: 3,
      constructionYear: 2018,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Estrada da Circunvalação, 234, Aldoar',
      images: ['https://exemplo.com/casa3-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-006',
      title: 'Apartamento T2 para Arrendar',
      description:
        'Apartamento T2 disponível para arrendamento em zona central, próximo a metro e universidades.',
      transactionType: 'arrendar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'D',
      price: 950,
      totalArea: 80,
      builtArea: 75,
      usefulArea: 70,
      bedrooms: 2,
      bathrooms: 1,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 0,
      constructionYear: 2010,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua de Costa Cabral, 1200, Paranhos',
      images: ['https://exemplo.com/apt3-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-007',
      title: 'Moradia Geminada T4 Nova',
      description:
        'Moradia geminada T4 de construção recente, com excelentes acabamentos, jardim e garagem para 2 carros.',
      transactionType: 'comprar',
      propertyType: 'Moradia',
      isEmpreendimento: false,
      propertyState: 'novo',
      energyClass: 'A',
      price: 580000,
      totalArea: 220,
      builtArea: 200,
      usefulArea: 185,
      bedrooms: 4,
      bathrooms: 3,
      hasOffice: false,
      hasLaundry: true,
      garageSpaces: 2,
      constructionYear: 2022,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua do Amial, 78, Ramalde',
      images: ['https://exemplo.com/casa4-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-008',
      title: 'Apartamento T3 Vista Mar',
      description:
        'Apartamento T3 com vista mar espetacular, varanda ampla, localizado em zona premium.',
      transactionType: 'comprar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'B',
      price: 650000,
      totalArea: 150,
      builtArea: 140,
      usefulArea: 130,
      bedrooms: 3,
      bathrooms: 2,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 2,
      constructionYear: 2016,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Avenida Brasil, 450, 10º andar, Foz do Douro',
      images: ['https://exemplo.com/apt4-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-009',
      title: 'Estúdio Mobilado Centro',
      description:
        'Estúdio totalmente mobilado e equipado no centro da cidade, ideal para estudantes ou profissionais.',
      transactionType: 'arrendar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'E',
      price: 650,
      totalArea: 38,
      builtArea: 35,
      usefulArea: 32,
      bedrooms: 0,
      bathrooms: 1,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 0,
      constructionYear: 2005,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua de Cedofeita, 345, 1º andar, Cedofeita',
      images: ['https://exemplo.com/studio1-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-010',
      title: 'Vivenda de Luxo com 6 Quartos',
      description:
        'Vivenda de luxo com 6 quartos, piscina infinity, cinema privado, ginásio e spa. Acabamentos premium.',
      transactionType: 'comprar',
      propertyType: 'Vivenda',
      isEmpreendimento: false,
      propertyState: 'novo',
      energyClass: 'A+',
      price: 2500000,
      totalArea: 550,
      builtArea: 500,
      usefulArea: 450,
      bedrooms: 6,
      bathrooms: 5,
      hasOffice: true,
      hasLaundry: true,
      garageSpaces: 4,
      constructionYear: 2021,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua Particular de Campo Alegre, 12, Campo Alegre',
      images: ['https://exemplo.com/vivenda1-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-011',
      title: 'Apartamento T2 Renovado',
      description:
        'Apartamento T2 recentemente renovado, com cozinha equipada e ar condicionado em todos os quartos.',
      transactionType: 'arrendar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'renovado',
      energyClass: 'C',
      price: 1100,
      totalArea: 85,
      builtArea: 80,
      usefulArea: 75,
      bedrooms: 2,
      bathrooms: 1,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 1,
      constructionYear: 1990,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua de Fernandes Tomás, 789, Bonfim',
      images: ['https://exemplo.com/apt5-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-012',
      title: 'Casa Térrea com Piscina T3',
      description:
        'Casa térrea espaçosa com piscina, jardim e churrasqueira. Perfeita para lazer em família.',
      transactionType: 'comprar',
      propertyType: 'Casa',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'B',
      price: 520000,
      totalArea: 210,
      builtArea: 190,
      usefulArea: 175,
      bedrooms: 3,
      bathrooms: 2,
      hasOffice: false,
      hasLaundry: true,
      garageSpaces: 2,
      constructionYear: 2017,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua de São Tomé, 156, Campanhã',
      images: ['https://exemplo.com/casa5-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-013',
      title: 'Apartamento Duplex T4 Luxo',
      description:
        'Apartamento duplex T4 de luxo com terraço privativo, vista panorâmica e garagem dupla.',
      transactionType: 'comprar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'novo',
      energyClass: 'A',
      price: 890000,
      totalArea: 220,
      builtArea: 200,
      usefulArea: 185,
      bedrooms: 4,
      bathrooms: 3,
      hasOffice: true,
      hasLaundry: true,
      garageSpaces: 2,
      constructionYear: 2019,
      distrito: 'Porto',
      concelho: 'Porto',
      address:
        'Praça de Mouzinho de Albuquerque, 90, Penthouse, Rotunda da Boavista',
      images: ['https://exemplo.com/apt6-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-014',
      title: 'Moradia com 8 Quartos - Ideal Investimento',
      description:
        'Moradia ampla com 8 quartos, ideal para investimento ou grande família. Localização central.',
      transactionType: 'comprar',
      propertyType: 'Moradia',
      isEmpreendimento: false,
      propertyState: 'usado',
      energyClass: 'D',
      price: 750000,
      totalArea: 300,
      builtArea: 280,
      usefulArea: 260,
      bedrooms: 8,
      bathrooms: 4,
      hasOffice: false,
      hasLaundry: true,
      garageSpaces: 2,
      constructionYear: 1980,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua de Gonçalo Cristóvão, 234, Miragaia',
      images: ['https://exemplo.com/casa6-1.jpg'],
      status: 'active',
    },
    {
      reference: 'REF-015',
      title: 'Apartamento T3 Novo Próximo Universidade',
      description:
        'Apartamento T3 novo, próximo à Universidade do Porto, ideal para arrendamento a estudantes.',
      transactionType: 'arrendar',
      propertyType: 'Apartamento',
      isEmpreendimento: false,
      propertyState: 'novo',
      energyClass: 'A',
      price: 1200,
      totalArea: 105,
      builtArea: 95,
      usefulArea: 88,
      bedrooms: 3,
      bathrooms: 2,
      hasOffice: false,
      hasLaundry: false,
      garageSpaces: 1,
      constructionYear: 2023,
      distrito: 'Porto',
      concelho: 'Porto',
      address: 'Rua do Campo Alegre, 600, Campo Alegre',
      images: ['https://exemplo.com/apt7-1.jpg'],
      status: 'active',
    },
  ];

  console.log('🌱 Iniciando seed do banco de dados...\n');

  for (const property of properties) {
    try {
      await propertiesService.create(property as any);
      console.log(`✅ Criado: ${property.title}`);
    } catch (error) {
      console.error(`❌ Erro ao criar ${property.title}:`, error.message);
    }
  }

  console.log('\n✨ Seed concluído!');
  await app.close();
}

bootstrap();
